# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('top_type', models.CharField(max_length=50)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Track')),
            ],
        ),
    ]
