# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20161030_0308'),
        ('tracks', '0002_top'),
        ('tracks', '0002_auto_20161029_2349'),
    ]

    operations = [
    ]
