# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 15:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_auto_20161101_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
    ]
