# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0014_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracks.Gender'),
        ),
    ]
