# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/avatars/')),
                ('artistic_name', models.CharField(blank=True, max_length=50)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_account_type', models.CharField(choices=[('AH', 'Ahorros'), ('CR', 'Corriente'), ('NA', '')], default='NA', max_length=2)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('telephone_number', models.CharField(blank=True, max_length=15)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
