# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161029_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuser',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
