# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_donation'),
        ('users', '0004_auto_20161029_2256'),
    ]

    operations = [
    ]
