language: python
python:
- 3.5.2
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: PekJe9FTfb38SeIkwTQOAIbdeyb9CKqKfj2A58lzeClyBVfpzhiW+zvAWbgywOaWHd4oyrJDyhwGg8zeZumBntiZKW9tIJDSAJz2ShUNtcWKuyDB66Z58uTINwkcP42G25VAPvqe2+6/kR5ls2g3TaV4im5vAzRIeGuuM97UPD/Z2Wg8mWhimtUWVmqHULksJh/NAHyOMXxsmaDxfh/pFN0Qb6JGQtjGezDdEG48XcauS9IeNaIJ8f5pWoJ+05WXrD5QHUdy9I+g0t4XXdmbhOiDHDSSR1JSyNNtjzSAzex+LylwrL+Tei22//6XzDn91RKIclbdgd6yp9zH2XqFGeRWQ5xer8qi8P6Y8GgSNeziaAMeSJ5/1KQA1tgWxnNWAXBwlUcnk4Ww1R6sJbHOOkao++emR4Dh6rZ1Scy5H/13B88r+4s6/iuyBNahXJS3GdfGOckPMsJ7iwbIU8GInR33WYejCLNu3yGSmzn/RlIaDK1SQCrCi7vvxIYC8FD22jYhs+i2v6p+b8O+jEF5kFyg7jwFoccAi9ZrXAjMbQHED2ThGdKQ3OEfzTzAfgM3HBEGWc/G9EJ7lyYg2xZpXQ8TUB6QEICk2j60Fe1wNFhzwPgYFzXc4vvUeuV3OcV/hBx8QHAGxo6q+tc9xh17CY5HXqklJEiyjXbAOs4onU8=
  app:
     # https://freeven-srv.herokuapp.com
    master: freeven-srv
     # https://freeven-srv-stg.herokuapp.com
    stage: freeven-srv-stg
     # https://freeven-srv-dev.herokuapp.com
    development: freeven-srv-dev
  on:
    repo: Rocket-Team/Freeven-srv
  run:
  - python manage.py collectstatic --no-input --settings=freeven.settings.prod
notifications:
  slack:
    secure: Be/DLvDnNODxS52xn3+KBj2Q7O4WO7wYttcS6ZmvdbJKfPuzT0aa25l6NlcH9aFjBLQ5goODA3/hY+dSsiyBfKQLKh+toUn4+T5Rw42ilBPR0dcnzdHDwiPTTbvHABQLQYsuPbBwmrETYZCug9s5W4eevgxxx0TtLYtWXKCnBSwTzzVdRt0X0zuJOmovs3qOHMT1gJoXGb72Nx/toBcNwths00UdpZ3mG2lWTWjecjNKf+49uwqdUvMiKPtbGf+bDojgmVCb1jf1g0XwVu6U92GpOZNMMb4DRLwblsRTdYKYA8hddfDqNYSyBplHpfqlMRKonmMDLo5iD8O8aRI/hQZWBVk9m+5AguVN/akavJSbfZQ7b7UlkqkNmbUAoJFwmtrj4PkfGS4cCJMVzbtAvLvtnthevWsRMh7IRXxwoZQ1pGxqVZ3RHIRkFXOj0ddSSVlGtB5yDnW3blSH0ghRT3jCIgttd99IUyzdAEtLuQftzOmd7YB6UNn887+B930O0r822MJA3XlzYlvt1waay2lBr4IqQeOJ4WUvq0rFheCFay8NQsbVPLWB1UUSJR7qisRNtL/EQOrPoOeE2OWD6lyi5TXexcRy4OozZLhXAOdb0FKjhQTV06gC7oIHFdRVMojVkVbwP9gLgFogpayEmwqheMgWzbydYxnGVKvXLvw=
