# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='state',
            new_name='open',
        ),
    ]
