# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20161113_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='ancts', to='tracks.Track'),
        ),
    ]
