# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20161113_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tracks',
            field=models.ManyToManyField(related_name='ancts', to='tracks.Track'),
        ),
    ]
